name: 'setup-dart'
description: 'GitHub Action that sets up the Dart SDK in a CI VM.'
author: 'Renato Athaydes'
inputs:
  dart-version:
    description: 'Dart SDK Version'
    default: '2.4.1'
runs:
  using: 'node12'
  main: 'lib/main.js'
