name: 'setup-dart'
description: 'GitHub Action that sets up the Dart SDK in a CI VM.'
author: 'Renato Athaydes'
inputs:
  dart-version:
    description: 'Dart SDK Version'
    default: '2.4.1'
  dart-channel:
    description: 'Dart release channel (dev, stable)'
    default: 'stable'
  architecture:
    description: 'The architecture of the VM running the job'
    default: 'x64'
runs:
  using: 'node12'
  main: 'lib/main.js'
